language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - $ANDROID_TARGET
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 100M
  - emulator -avd test -no-window &
  - bash ./tools/android-wait-for-emulator.sh
  - adb shell input keyevent 82 &

script:
  - bash ./gradlew build
  - bash ./gradlew test -x lint --stacktrace
